module IngredientsHelper

  #generates options array from the ingredients hash for <select> tags in forms
  #pass it a symbol for the ingredient type (either :malts, :hops, or :yeasts)
  def options_generator(ingredient_type)
    return if ingredients[ingredient_type] == nil

    options = Array.new

    ingredients[ingredient_type].each do |key, value|
      option = Array.new.tap do |option|
        option.push value[:name]
        option.push key
      end
      options.push option
    end
    return options
  end

  #system default ingredients are stored here as a hash
  def ingredients
    {
      malts: { #colour vals in SRM
        :acid_malt=>{:name=>"Acid Malt", :origin=>"Germany", :type=>"Grain", :colour=>3, :must_mash=>true, :ppg=>1.027},
        :amber_dry_extract=>{:name=>"Amber Dry Extract", :origin=>"US", :type=>"Dry Extract", :colour=>13, :must_mash=>false, :ppg=>1.044},
        :amber_liquid_extract=>{:name=>"Amber Liquid Extract", :origin=>"US", :type=>"Extract", :colour=>13, :must_mash=>false, :ppg=>1.036},
        :amber_malt=>{:name=>"Amber Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>22, :must_mash=>true, :ppg=>1.035},
        :aromatic_malt=>{:name=>"Aromatic Malt", :origin=>"Belgium", :type=>"Grain", :colour=>26, :must_mash=>true, :ppg=>1.036},
        :barley_hulls=>{:name=>"Barley Hulls", :origin=>"US", :type=>"Adjunct", :colour=>0, :must_mash=>false, :ppg=>1.0},
        :barley_flaked=>{:name=>"Barley, Flaked", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.032},
        :barley_raw=>{:name=>"Barley, Raw", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.028},
        :barley_torrefied=>{:name=>"Barley, Torrefied", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.036},
        :biscuit_malt=>{:name=>"Biscuit Malt", :origin=>"Belgium", :type=>"Grain", :colour=>23, :must_mash=>false, :ppg=>1.036},
        :black_patent_malt=>{:name=>"Black Patent Malt", :origin=>"US", :type=>"Grain", :colour=>500, :must_mash=>false, :ppg=>1.025},
        :black_barley_stout=>{:name=>"Black Barley (Stout)", :origin=>"US", :type=>"Grain", :colour=>500, :must_mash=>false, :ppg=>1.025},
        :brown_malt=>{:name=>"Brown Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>65, :must_mash=>true, :ppg=>1.032},
        :brown_sugar_dark=>{:name=>"Brown Sugar, Dark", :origin=>"US", :type=>"Sugar", :colour=>50, :must_mash=>false, :ppg=>1.046},
        :brown_sugar_light=>{:name=>"Brown Sugar, Light", :origin=>"US", :type=>"Sugar", :colour=>8, :must_mash=>false, :ppg=>1.046},
        :brumalt=>{:name=>"Brumalt", :origin=>"Germany", :type=>"Grain", :colour=>23, :must_mash=>true, :ppg=>1.033},
        :candi_sugar_amber=>{:name=>"Candi Sugar, Amber", :origin=>"Belgium", :type=>"Sugar", :colour=>75, :must_mash=>false, :ppg=>1.036},
        :candi_sugar_clear=>{:name=>"Candi Sugar, Clear", :origin=>"Belgium", :type=>"Sugar", :colour=>1, :must_mash=>false, :ppg=>1.036},
        :candi_sugar_dark=>{:name=>"Candi Sugar, Dark", :origin=>"Belgium", :type=>"Sugar", :colour=>275, :must_mash=>false, :ppg=>1.036},
        :cane_sugar=>{:name=>"Cane (Beet) Sugar", :origin=>"US", :type=>"Sugar", :colour=>0, :must_mash=>false, :ppg=>1.046},
        :cara_pils_dextrine=>{:name=>"Cara-Pils/Dextrine", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>false, :ppg=>1.033},
        :cara_amber=>{:name=>"Caraamber", :origin=>"US", :type=>"Grain", :colour=>30, :must_mash=>false, :ppg=>1.035},
        :carafoam=>{:name=>"Carafoam", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>false, :ppg=>1.033},
        :crystal_malt_10L=>{:name=>"Crystal Malt 10L", :origin=>"US", :type=>"Grain", :colour=>10, :must_mash=>false, :ppg=>1.035},
        :crystal_malt_20L=>{:name=>"Crystal Malt 20L", :origin=>"US", :type=>"Grain", :colour=>20, :must_mash=>false, :ppg=>1.035},
        :crystal_malt_30L=>{:name=>"Crystal Malt 30L", :origin=>"US", :type=>"Grain", :colour=>30, :must_mash=>false, :ppg=>1.035},
        :crystal_malt_40L=>{:name=>"Crystal Malt 40L", :origin=>"US", :type=>"Grain", :colour=>40, :must_mash=>false, :ppg=>1.034},
        :crystal_malt_60L=>{:name=>"Crystal Malt 60L", :origin=>"US", :type=>"Grain", :colour=>60, :must_mash=>false, :ppg=>1.034},
        :crystal_malt_80L=>{:name=>"Crystal Malt 80L", :origin=>"US", :type=>"Grain", :colour=>80, :must_mash=>false, :ppg=>1.034},
        :crystal_malt_120L=>{:name=>"Crystal Malt 120L", :origin=>"US", :type=>"Grain", :colour=>120, :must_mash=>false, :ppg=>1.033},
        :caramunich_malt=>{:name=>"Caramunich Malt", :origin=>"Belgium", :type=>"Grain", :colour=>56, :must_mash=>false, :ppg=>1.033},
        :carared=>{:name=>"Carared", :origin=>"US", :type=>"Grain", :colour=>20, :must_mash=>false, :ppg=>1.035},
        :caravienne_malt=>{:name=>"Caravienne Malt", :origin=>"Belgium", :type=>"Grain", :colour=>22, :must_mash=>false, :ppg=>1.034},
        :chocolate_malt=>{:name=>"Chocolate Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>450, :must_mash=>false, :ppg=>1.034},
        :corn_sugar=>{:name=>"Corn Sugar (Dextrose)", :origin=>"US", :type=>"Sugar", :colour=>0, :must_mash=>false, :ppg=>1.046},
        :corn_syrup=>{:name=>"Corn Syrup", :origin=>"US", :type=>"Sugar", :colour=>1, :must_mash=>false, :ppg=>1.036},
        :corn_flaked=>{:name=>"Corn, Flaked", :origin=>"US", :type=>"Grain", :colour=>1, :must_mash=>true, :ppg=>1.037},
        :dark_dry_extract=>{:name=>"Dark Dry Extract", :origin=>"US", :type=>"Dry Extract", :colour=>18, :must_mash=>false, :ppg=>1.044},
        :dark_liquid_extract=>{:name=>"Dark Liquid Extract", :origin=>"US", :type=>"Extract", :colour=>18, :must_mash=>false, :ppg=>1.036},
        :dememera_sugar=>{:name=>"Dememera Sugar", :origin=>"United Kingdom", :type=>"Sugar", :colour=>2, :must_mash=>false, :ppg=>1.046},
        :extra_light_dry_extract=>{:name=>"Extra Light Dry Extract", :origin=>"US", :type=>"Dry Extract", :colour=>3, :must_mash=>false, :ppg=>1.044},
        :grits=>{:name=>"Grits", :origin=>"US", :type=>"Adjunct", :colour=>1, :must_mash=>false, :ppg=>1.037},
        :honey=>{:name=>"Honey", :origin=>"US", :type=>"Extract", :colour=>1, :must_mash=>false, :ppg=>1.035},
        :invert_sugar=>{:name=>"Invert Sugar", :origin=>"United Kingdom", :type=>"Sugar", :colour=>0, :must_mash=>false, :ppg=>1.046},
        :light_dry_extract=>{:name=>"Light Dry Extract", :origin=>"US", :type=>"Dry Extract", :colour=>8, :must_mash=>false, :ppg=>1.044},
        :maple_syrup=>{:name=>"Maple Syrup", :origin=>"US", :type=>"Sugar", :colour=>35, :must_mash=>false, :ppg=>1.030},
        :melanoiden_malt=>{:name=>"Melanoiden Malt", :origin=>"Germany", :type=>"Grain", :colour=>20, :must_mash=>true, :ppg=>1.037},
        :mild_malt=>{:name=>"Mild Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>4, :must_mash=>true, :ppg=>1.037},
        :lactose=>{:name=>"Milk Sugar (Lactose)", :origin=>"US", :type=>"Sugar", :colour=>0, :must_mash=>false, :ppg=>1.035},
        :molasses=>{:name=>"Molasses", :origin=>"US", :type=>"Sugar", :colour=>80, :must_mash=>false, :ppg=>1.036},
        :munich_malt=>{:name=>"Munich Malt", :origin=>"Germany", :type=>"Grain", :colour=>9, :must_mash=>true, :ppg=>1.037},
        :munich_malt_10L=>{:name=>"Munich Malt 10L", :origin=>"US", :type=>"Grain", :colour=>10, :must_mash=>true, :ppg=>1.035},
        :munich_malt_20L=>{:name=>"Munich Malt 20L", :origin=>"US", :type=>"Grain", :colour=>20, :must_mash=>true, :ppg=>1.035},
        :oats_flaked=>{:name=>"Oats, Flaked", :origin=>"US", :type=>"Grain", :colour=>1, :must_mash=>true, :ppg=>1.037},
        :oats_malted=>{:name=>"Oats, Malted", :origin=>"US", :type=>"Grain", :colour=>1, :must_mash=>true, :ppg=>1.037},
        :pale_liquid_extract=>{:name=>"Pale Liquid Extract", :origin=>"US", :type=>"Extract", :colour=>8, :must_mash=>false, :ppg=>1.036},
        :pale_malt_2=>{:name=>"Pale Malt (2 Row)", :origin=>"US", :type=>"Grain", :colour=>3, :must_mash=>true, :ppg=>1.037},
        :pale_malt_6=>{:name=>"Pale Malt (6 Row)", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.035},
        :peat_smoked_malt=>{:name=>"Peat Smoked Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>3, :must_mash=>true, :ppg=>1.034},
        :pilsner_2=>{:name=>"Pilsner (2 Row)", :origin=>"Germany", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.037},
        :pilsner_liquid_extract=>{:name=>"Pilsner Liquid Extract", :origin=>"US", :type=>"Extract", :colour=>4, :must_mash=>false, :ppg=>1.036},
        :rice_extract_syrup=>{:name=>"Rice Extract Syrup", :origin=>"US", :type=>"Extract", :colour=>7, :must_mash=>false, :ppg=>1.032},
        :rice_hulls=>{:name=>"Rice Hulls", :origin=>"US", :type=>"Adjunct", :colour=>0, :must_mash=>false, :ppg=>1.0},
        :rice_flaked=>{:name=>"Rice, Flaked", :origin=>"US", :type=>"Grain", :colour=>1, :must_mash=>true, :ppg=>1.032},
        :roasted_barley=>{:name=>"Roasted Barley", :origin=>"US", :type=>"Grain", :colour=>300, :must_mash=>false, :ppg=>1.025},
        :rye_malt=>{:name=>"Rye Malt", :origin=>"US", :type=>"Grain", :colour=>5, :must_mash=>true, :ppg=>1.029},
        :rye_flaked=>{:name=>"Rye, Flaked", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.036},
        :smoked_malt=>{:name=>"Smoked Malt", :origin=>"Germany", :type=>"Grain", :colour=>9, :must_mash=>true, :ppg=>1.037},
        :special_b_malt=>{:name=>"Special B Malt", :origin=>"Belgium", :type=>"Grain", :colour=>180, :must_mash=>true, :ppg=>1.03},
        :special_roast=>{:name=>"Special Roast", :origin=>"US", :type=>"Grain", :colour=>50, :must_mash=>true, :ppg=>1.033},
        :toasted_malt=>{:name=>"Toasted Malt", :origin=>"United Kingdom", :type=>"Grain", :colour=>27, :must_mash=>true, :ppg=>1.033},
        :turbinado=>{:name=>"Turbinado", :origin=>"United Kingdom", :type=>"Sugar", :colour=>10, :must_mash=>false, :ppg=>1.044},
        :victory_malt=>{:name=>"Victory Malt", :origin=>"US", :type=>"Grain", :colour=>25, :must_mash=>true, :ppg=>1.034},
        :vienna_malt=>{:name=>"Vienna Malt", :origin=>"Germany", :type=>"Grain", :colour=>4, :must_mash=>true, :ppg=>1.036},
        :wheat_dry_extract=>{:name=>"Wheat Dry Extract", :origin=>"US", :type=>"Dry Extract", :colour=>8, :must_mash=>false, :ppg=>1.044},
        :wheat_liquid_extract=>{:name=>"Wheat Liquid Extract", :origin=>"US", :type=>"Extract", :colour=>8, :must_mash=>false, :ppg=>1.036},
        :wheat_malt=>{:name=>"Wheat Malt", :origin=>"Belgium", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.037},
        :wheat_malt_dark=>{:name=>"Wheat Malt, Dark", :origin=>"Germany", :type=>"Grain", :colour=>9, :must_mash=>true, :ppg=>1.039},
        :wheat_flaked=>{:name=>"Wheat, Flaked", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.035},
        :wheat_roasted=>{:name=>"Wheat, Roasted", :origin=>"Germany", :type=>"Grain", :colour=>425, :must_mash=>true, :ppg=>1.025},
        :wheat_torrified=>{:name=>"Wheat, Torrified", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.036},
        :white_wheat_malt=>{:name=>"White Wheat Malt", :origin=>"US", :type=>"Grain", :colour=>2, :must_mash=>true, :ppg=>1.04}
      },
      hops: {
        :admiral=>{:name=>"Admiral", :origin=>"UK", :aa=>14.8, :type=>"Bittering"},
        :ahtanum=>{:name=>"Ahtanum", :origin=>"US", :aa=>6.0, :type=>"Aroma"},
        :amarillo_gold=>{:name=>"Amarillo Gold", :origin=>"US", :aa=>8.5, :type=>"Aroma"},
        :aquila=>{:name=>"Aquila", :origin=>"US", :aa=>6.5, :type=>"Aroma"},
        :banner=>{:name=>"Banner", :origin=>"US", :aa=>10.0, :type=>"Bittering"},
        :bramling_cross=>{:name=>"Bramling Cross", :origin=>"UK", :aa=>6.0, :type=>"Aroma"},
        :brewers_gold=>{:name=>"Brewers Gold", :origin=>"UK", :aa=>8.0, :type=>"Bittering"},
        :bullion=>{:name=>"Bullion", :origin=>"UK", :aa=>8.0, :type=>"Bittering"},
        :cascade=>{:name=>"Cascade", :origin=>"US", :aa=>5.5, :type=>"Both"},
        :centennial=>{:name=>"Centennial", :origin=>"US", :aa=>10.0, :type=>"Bittering"},
        :challenger=>{:name=>"Challenger", :origin=>"UK", :aa=>7.5, :type=>"Aroma"},
        :chinook=>{:name=>"Chinook", :origin=>"US", :aa=>13.0, :type=>"Bittering"},
        :cluster=>{:name=>"Cluster", :origin=>"US", :aa=>7.0, :type=>"Bittering"},
        :columbia=>{:name=>"Columbia", :origin=>"UK", :aa=>5.5, :type=>"Bittering"},
        :columbus_tomahawk=>{:name=>"Columbus (Tomahawk)", :origin=>"US", :aa=>14.0, :type=>"Bittering"},
        :comet=>{:name=>"Comet", :origin=>"US", :aa=>9.5, :type=>"Bittering"},
        :crystal=>{:name=>"Crystal", :origin=>"US", :aa=>3.5, :type=>"Aroma"},
        :eroica=>{:name=>"Eroica", :origin=>"US", :aa=>13.0, :type=>"Bittering"},
        :first_gold=>{:name=>"First Gold", :origin=>"UK", :aa=>7.5, :type=>"Both"},
        :fuggles=>{:name=>"Fuggles", :origin=>"UK", :aa=>4.5, :type=>"Aroma"},
        :galena=>{:name=>"Galena", :origin=>"US", :aa=>13.0, :type=>"Bittering"},
        :glacier=>{:name=>"Glacier", :origin=>"US", :aa=>5.6, :type=>"Aroma"},
        :goldings_bc=>{:name=>"Goldings, Brit. Col.", :origin=>"Canada", :aa=>5.0, :type=>"Aroma"},
        :goldings_ek=>{:name=>"Goldings, EK", :origin=>"UK", :aa=>5.0, :type=>"Aroma"},
        :green_bullet=>{:name=>"Green Bullet", :origin=>"New Zealand", :aa=>13.5, :type=>"Bittering"},
        :hallertauer=>{:name=>"Hallertauer", :origin=>"Germany", :aa=>4.8, :type=>"Aroma"},
        :hallertauer_hersbrucker=>{:name=>"Hallertauer, Hersbrucker", :origin=>"Germany", :aa=>4.0, :type=>"Aroma"},
        :hallertauer_mittelfrueh=>{:name=>"Hallertauer, Mittelfrueh", :origin=>"Germany", :aa=>4.0, :type=>"Aroma"},
        :hallertauer_nz=>{:name=>"Hallertauer, New Zealand", :origin=>"New Zealand", :aa=>8.5, :type=>"Both"},
        :herald=>{:name=>"Herald", :origin=>"UK", :aa=>12.0, :type=>"Bittering"},
        :horizon=>{:name=>"Horizon", :origin=>"US", :aa=>12.0, :type=>"Bittering"},
        :liberty=>{:name=>"Liberty", :origin=>"US", :aa=>4.3, :type=>"Aroma"},
        :lublin=>{:name=>"Lublin", :origin=>"Poland", :aa=>5.0, :type=>"Bittering"},
        :magnum=>{:name=>"Magnum", :origin=>"Germany", :aa=>14.0, :type=>"Bittering"},
        :mt_hood=>{:name=>"Mt. Hood", :origin=>"US", :aa=>6.0, :type=>"Aroma"},
        :northdown=>{:name=>"Northdown", :origin=>"UK", :aa=>8.5, :type=>"Both"},
        :northern_brewer=>{:name=>"Northern Brewer", :origin=>"Germany", :aa=>8.5, :type=>"Both"},
        :nugget=>{:name=>"Nugget", :origin=>"US", :aa=>13.0, :type=>"Bittering"},
        :orion=>{:name=>"Orion", :origin=>"Germany", :aa=>7.3, :type=>"Both"},
        :pacific_gem=>{:name=>"Pacific Gem", :origin=>"New Zealand", :aa=>15.0, :type=>"Bittering"},
        :pearle=>{:name=>"Pearle", :origin=>"Germany", :aa=>8.0, :type=>"Bittering"},
        :phoenix=>{:name=>"Phoenix", :origin=>"UK", :aa=>8.0, :type=>"Bittering"},
        :pilgrim=>{:name=>"Pilgrim", :origin=>"UK", :aa=>11.5, :type=>"Bittering"},
        :pioneer=>{:name=>"Pioneer", :origin=>"UK", :aa=>9.0, :type=>"Both"},
        :pride_of_ringwood=>{:name=>"Pride of Ringwood", :origin=>"Australia", :aa=>9.0, :type=>"Bittering"},
        :progress=>{:name=>"Progress", :origin=>"UK", :aa=>6.3, :type=>"Aroma"},
        :saaz=>{:name=>"Saaz", :origin=>"Czech Rep.", :aa=>4.0, :type=>"Aroma"},
        :santiam=>{:name=>"Santiam", :origin=>"US", :aa=>6.0, :type=>"Aroma"},
        :select_spalt=>{:name=>"Select Spalt", :origin=>"Germany", :aa=>4.8, :type=>"Aroma"},
        :southern_cross=>{:name=>"Southern Cross", :origin=>"New Zealand", :aa=>13.0, :type=>"Both"},
        :spalter=>{:name=>"Spalter", :origin=>"Germany", :aa=>4.5, :type=>"Aroma"},
        :sterling=>{:name=>"Sterling", :origin=>"US", :aa=>7.5, :type=>"Both"},
        :sticklebract=>{:name=>"Sticklebract", :origin=>"New Zealand", :aa=>13.5, :type=>"Both"},
        :strisselspalt=>{:name=>"Strisselspalt", :origin=>"France", :aa=>4.0, :type=>"Aroma"},
        :styrian_goldings=>{:name=>"Styrian Goldings", :origin=>"Slovenia", :aa=>5.4, :type=>"Aroma"},
        :sun=>{:name=>"Sun", :origin=>"US", :aa=>14.0, :type=>"Bittering"},
        :super_alpha=>{:name=>"Super Alpha", :origin=>"New Zealand", :aa=>13.0, :type=>"Bittering"},
        :target=>{:name=>"Target", :origin=>"UK", :aa=>11.0, :type=>"Bittering"},
        :tettnang=>{:name=>"Tettnang", :origin=>"Germany", :aa=>4.5, :type=>"Aroma"},
        :tradition=>{:name=>"Tradition", :origin=>"Germany", :aa=>6.0, :type=>"Bittering"},
        :ultra=>{:name=>"Ultra", :origin=>"US", :aa=>3.0, :type=>"Aroma"},
        :vanguard=>{:name=>"Vanguard", :origin=>"US", :aa=>5.5, :type=>"Aroma"},
        :warrior=>{:name=>"Warrior", :origin=>"US", :aa=>15.0, :type=>"Both"},
        :whitbread_gv=>{:name=>"Whitbread Golding Var", :origin=>"UK", :aa=>6.0, :type=>"Aroma"},
        :willamette=>{:name=>"Willamette", :origin=>"US", :aa=>5.5, :type=>"Aroma"},
        :zeus=>{:name=>"Zeus", :origin=>"US", :aa=>14.0, :type=>"Bittering"}
      },
      yeasts: {
        :coopers_ale=>{:name=>"Coopers Ale", :lab=>"Coopers", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :doric_ale=>{:name=>"Doric Ale", :lab=>"Doric", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :edme_ale=>{:name=>"Edme Ale Yeast", :lab=>"Edme", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :danstar_nottingham_ale=>{:name=>"Nottingham", :lab=>"Danstar", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"High"},
        :munton_fison_ale=>{:name=>"Munton Fison Ale", :lab=>"Munton-Fison", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :lallemand_windsor_ale=>{:name=>"Windsor Yeast", :lab=>"Lallemand", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Very High"},
        :red_star_ale=>{:name=>"Red Star Ale", :lab=>"Red Star", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :glenbrew_special_ale=>{:name=>"Special Ale", :lab=>"Glenbrew", :number=>"", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :wyeast_labs_1007=>{:name=>"German Ale", :lab=>"Wyeast Labs", :number=>"1007", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_1010=>{:name=>"American Wheat Ale", :lab=>"Wyeast Labs", :number=>"1010", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_1026=>{:name=>"British Cask Ale", :lab=>"Wyeast Labs", :number=>"1026", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1028=>{:name=>"London Ale", :lab=>"Wyeast Labs", :number=>"1028", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1056=>{:name=>"American Ale", :lab=>"Wyeast Labs", :number=>"1056", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1084=>{:name=>"Irish Ale", :lab=>"Wyeast Labs", :number=>"1084", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1087=>{:name=>"Wyeast Ale Blend", :lab=>"Wyeast Labs", :number=>"1087", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1098=>{:name=>"British Ale", :lab=>"Wyeast Labs", :number=>"1098", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1099=>{:name=>"Whitbread Ale", :lab=>"Wyeast Labs", :number=>"1099", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1187=>{:name=>"Ringwood Ale", :lab=>"Wyeast Labs", :number=>"1187", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1214=>{:name=>"Belgian Ale", :lab=>"Wyeast Labs", :number=>"1214", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1272=>{:name=>"GF All American Ale", :lab=>"Wyeast Labs", :number=>"1272", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1275=>{:name=>"Thames Valley Ale", :lab=>"Wyeast Labs", :number=>"1275", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1318=>{:name=>"London Ale III", :lab=>"Wyeast Labs", :number=>"1318", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1332=>{:name=>"Northwest Ale", :lab=>"Wyeast Labs", :number=>"1332", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1335=>{:name=>"British Ale II", :lab=>"Wyeast Labs", :number=>"1335", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1338=>{:name=>"European Ale", :lab=>"Wyeast Labs", :number=>"1338", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1388=>{:name=>"Belgian Strong Ale", :lab=>"Wyeast Labs", :number=>"1388", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_1728=>{:name=>"Scottish Ale", :lab=>"Wyeast Labs", :number=>"1728", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_1762=>{:name=>"Belgian Abbey II", :lab=>"Wyeast Labs", :number=>"1762", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_1968=>{:name=>"London ESB Ale", :lab=>"Wyeast Labs", :number=>"1968", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_2000=>{:name=>"Budvar Lager", :lab=>"Wyeast Labs", :number=>"2000", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_2001=>{:name=>"Urquell Lager", :lab=>"Wyeast Labs", :number=>"2001", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2007=>{:name=>"Pilsen Lager", :lab=>"Wyeast Labs", :number=>"2007", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2035=>{:name=>"American Lager", :lab=>"Wyeast Labs", :number=>"2035", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2042=>{:name=>"Danish Lager", :lab=>"Wyeast Labs", :number=>"2042", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2112=>{:name=>"California Lager", :lab=>"Wyeast Labs", :number=>"2112", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_2124=>{:name=>"Bohemian Lager", :lab=>"Wyeast Labs", :number=>"2124", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2178=>{:name=>"Wyeast Lager Blend", :lab=>"Wyeast Labs", :number=>"2178", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2206=>{:name=>"Bavarian Lager", :lab=>"Wyeast Labs", :number=>"2206", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2247=>{:name=>"European Lager II", :lab=>"Wyeast Labs", :number=>"2247", :type=>"Lager", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_2272=>{:name=>"North American Lager", :lab=>"Wyeast Labs", :number=>"2272", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_2278=>{:name=>"Czech Pilsner Lager", :lab=>"Wyeast Labs", :number=>"2278", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2308=>{:name=>"Munich Lager", :lab=>"Wyeast Labs", :number=>"2308", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_2565=>{:name=>"Kolsch Yeast", :lab=>"Wyeast Labs", :number=>"2565", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3056=>{:name=>"Bavarian Wheat Yeast", :lab=>"Wyeast Labs", :number=>"3056", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_3068=>{:name=>"Weihenstephan Weizen", :lab=>"Wyeast Labs", :number=>"3068", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3112=>{:name=>"Brettanomyces bruxellensis", :lab=>"Wyeast Labs", :number=>"3112", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_3278=>{:name=>"Belgian Lambic Blend", :lab=>"Wyeast Labs", :number=>"3278", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3333=>{:name=>"German Wheat", :lab=>"Wyeast Labs", :number=>"3333", :type=>"Wheat", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_3463=>{:name=>"Forbidden Fruit", :lab=>"Wyeast Labs", :number=>"3463", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3522=>{:name=>"Belgian Ardennes", :lab=>"Wyeast Labs", :number=>"3522", :type=>"Wheat", :form=>"Liquid", :flocculation=>"High"},
        :wyeast_labs_3638=>{:name=>"Bavarian Wheat", :lab=>"Wyeast Labs", :number=>"3638", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3724=>{:name=>"Belgian Saison", :lab=>"Wyeast Labs", :number=>"3724", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :wyeast_labs_3763=>{:name=>"Roselare Belgian Blend", :lab=>"Wyeast Labs", :number=>"3763", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_3787=>{:name=>"Trappist High Gravity", :lab=>"Wyeast Labs", :number=>"3787", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_3942=>{:name=>"Belgian Wheat Yeast", :lab=>"Wyeast Labs", :number=>"3942", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_3944=>{:name=>"Belgian Witbier", :lab=>"Wyeast Labs", :number=>"3944", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_4335=>{:name=>"Lactobacillus Delbrueckii", :lab=>"Wyeast Labs", :number=>"4335", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :wyeast_labs_4733=>{:name=>"Pediococcus Cerevisiae", :lab=>"Wyeast Labs", :number=>"4733", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0010=>{:name=>"American Microbrewery Ale #1", :lab=>"Brewtek", :number=>"CL-0010", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0020=>{:name=>"American Microbrewery Ale #2", :lab=>"Brewtek", :number=>"CL-0020", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0060=>{:name=>"Noth-Eastern Micro Ale", :lab=>"Brewtek", :number=>"CL-0060", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0110=>{:name=>"British Microbrewery Ale", :lab=>"Brewtek", :number=>"CL-0110", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0120=>{:name=>"British Pale Ale #1", :lab=>"Brewtek", :number=>"CL-0120", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0130=>{:name=>"British Pale Ale #2", :lab=>"Brewtek", :number=>"CL-0130", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0150=>{:name=>"British Real Ale", :lab=>"Brewtek", :number=>"CL-0150", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0160=>{:name=>"British Draft Ale", :lab=>"Brewtek", :number=>"CL-0160", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0170=>{:name=>"Classic British Ale", :lab=>"Brewtek", :number=>"CL-0170", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0240=>{:name=>"Irish Dry Stout", :lab=>"Brewtek", :number=>"CL-0240", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0260=>{:name=>"Canadian Ale", :lab=>"Brewtek", :number=>"CL-0260", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0300=>{:name=>"Belgian Ale #1", :lab=>"Brewtek", :number=>"CL-0300", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0320=>{:name=>"Belgian Ale #2", :lab=>"Brewtek", :number=>"CL-0320", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :brewtek_cl_0340=>{:name=>"Belgian Ale #3", :lab=>"Brewtek", :number=>"CL-0340", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0380=>{:name=>"Saison", :lab=>"Brewtek", :number=>"CL-0380", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0400=>{:name=>"Old German Ale", :lab=>"Brewtek", :number=>"CL-0400", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0600=>{:name=>"Original Pilsner", :lab=>"Brewtek", :number=>"CL-0600", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0620=>{:name=>"American Megabrewery", :lab=>"Brewtek", :number=>"CL-0620", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0630=>{:name=>"American Microbrewery Lager", :lab=>"Brewtek", :number=>"CL-0630", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0650=>{:name=>"Old Bavarian Lager", :lab=>"Brewtek", :number=>"CL-0650", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0660=>{:name=>"Northern German Lager", :lab=>"Brewtek", :number=>"CL-0660", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0680=>{:name=>"East European Lager", :lab=>"Brewtek", :number=>"CL-0680", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0690=>{:name=>"California Esteem", :lab=>"Brewtek", :number=>"CL-0690", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0900=>{:name=>"Belgian Wheat", :lab=>"Brewtek", :number=>"CL-0900", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0920=>{:name=>"German Wheat", :lab=>"Brewtek", :number=>"CL-0920", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0930=>{:name=>"German Weiss", :lab=>"Brewtek", :number=>"CL-0930", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_0980=>{:name=>"American White Ale", :lab=>"Brewtek", :number=>"CL-0980", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :brewtek_cl_5200=>{:name=>"Brettanomyces lambicus", :lab=>"Brewtek", :number=>"CL-5200", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :brewtek_cl_5600=>{:name=>"Pediococcus damnosus", :lab=>"Brewtek", :number=>"CL-5600", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :lallemand_lalvin_71b_1122=>{:name=>"Lalvin 71B-1122", :lab=>"Lallemand - Lalvin", :number=>"71B-1122", :type=>"Wine", :form=>"Dry", :flocculation=>"High"},
        :lallemand_lalvin_d47=>{:name=>"Lalvin D-47", :lab=>"Lallemand - Lalvin", :number=>"D-47", :type=>"Wine", :form=>"Dry", :flocculation=>"High"},
        :lallemand_lalvin_ec1118=>{:name=>"Lalvin EC-1118", :lab=>"Lallemand - Lalvin", :number=>"EC-1118", :type=>"Wine", :form=>"Dry", :flocculation=>"High"},
        :lallemand_lalvin_k1v1116=>{:name=>"Lalvin - K1V-1116", :lab=>"Lallemand - Lalvin", :number=>"K1V-1116", :type=>"Wine", :form=>"Dry", :flocculation=>"Medium"},
        :lallemand_lalvin_rc212=>{:name=>"Lalvin RC 212 (Bourgovin)", :lab=>"Lallemand - Lalvin", :number=>"RC 212", :type=>"Wine", :form=>"Dry", :flocculation=>"Medium"},
        :dcl_yeast_k97=>{:name=>"SafAle German Ale", :lab=>"DCL Yeast", :number=>"K-97", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :dcl_yeast_s04=>{:name=>"SafAle English Ale", :lab=>"DCL Yeast", :number=>"S-04", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :dcl_yeast_s189=>{:name=>"SafLager German Lager", :lab=>"DCL Yeast", :number=>"S-189", :type=>"Lager", :form=>"Dry", :flocculation=>"High"},
        :dcl_yeast_s23=>{:name=>"SafLager West European Lager", :lab=>"DCL Yeast", :number=>"S-23", :type=>"Lager", :form=>"Dry", :flocculation=>"High"},
        :dcl_yeast_s33=>{:name=>"SafBrew Ale", :lab=>"DCL Yeast", :number=>"S-33", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :dcl_yeast_t58=>{:name=>"SafBrew Specialty Ale", :lab=>"DCL Yeast", :number=>"T-58", :type=>"Ale", :form=>"Dry", :flocculation=>"Medium"},
        :white_labs_wlp001=>{:name=>"California Ale", :lab=>"White Labs", :number=>"WLP001", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp002=>{:name=>"English Ale", :lab=>"White Labs", :number=>"WLP002", :type=>"Ale", :form=>"Liquid", :flocculation=>"Very High"},
        :white_labs_wlp003=>{:name=>"German Ale II", :lab=>"White Labs", :number=>"WLP003", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp004=>{:name=>"Irish Ale", :lab=>"White Labs", :number=>"WLP004", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp005=>{:name=>"British Ale", :lab=>"White Labs", :number=>"WLP005", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp006=>{:name=>"Bedford British Ale", :lab=>"White Labs", :number=>"WLP006", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp007=>{:name=>"Dry English Ale", :lab=>"White Labs", :number=>"WLP007", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp008=>{:name=>"East Coast Ale", :lab=>"White Labs", :number=>"WLP008", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp009=>{:name=>"Australian Ale Yeast", :lab=>"White Labs", :number=>"WLP009", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp011=>{:name=>"European Ale", :lab=>"White Labs", :number=>"WLP011", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp013=>{:name=>"London Ale", :lab=>"White Labs", :number=>"WLP013", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp022=>{:name=>"Essex Ale Yeast", :lab=>"White Labs", :number=>"WLP022", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp023=>{:name=>"Burton Ale", :lab=>"White Labs", :number=>"WLP023", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp025=>{:name=>"Southwold Ale", :lab=>"White Labs", :number=>"WLP025", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp026=>{:name=>"Premium Bitter Ale", :lab=>"White Labs", :number=>"WLP026", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp028=>{:name=>"Edinburgh Ale", :lab=>"White Labs", :number=>"WLP028", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp029=>{:name=>"German Ale/Kolsch", :lab=>"White Labs", :number=>"WLP029", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp033=>{:name=>"Klassic Ale Yeast", :lab=>"White Labs", :number=>"WLP033", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp036=>{:name=>"Dusseldorf Alt Yeast", :lab=>"White Labs", :number=>"WLP036", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp039=>{:name=>"Nottingham Ale Yeast", :lab=>"White Labs", :number=>"WLP039", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp041=>{:name=>"Pacific Ale", :lab=>"White Labs", :number=>"WLP041", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp051=>{:name=>"California Ale V", :lab=>"White Labs", :number=>"WLP051", :type=>"Ale", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp099=>{:name=>"Super High Gravity Ale", :lab=>"White Labs", :number=>"WLP099", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp300=>{:name=>"Hefeweizen Ale", :lab=>"White Labs", :number=>"WLP300", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp320=>{:name=>"American Hefeweizen Ale", :lab=>"White Labs", :number=>"WLP320", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp351=>{:name=>"Bavarian Weizen Yeast", :lab=>"White Labs", :number=>"WLP351", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp380=>{:name=>"Hefeweizen IV Ale", :lab=>"White Labs", :number=>"WLP380", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp400=>{:name=>"Belgian Wit Ale", :lab=>"White Labs", :number=>"WLP400", :type=>"Wheat", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp410=>{:name=>"Belgian Wit II", :lab=>"White Labs", :number=>"WLP410", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp500=>{:name=>"Trappist Ale", :lab=>"White Labs", :number=>"WLP500", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp510=>{:name=>"Bastogne Belgian Ale", :lab=>"White Labs", :number=>"WLP510", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp530=>{:name=>"Abbey Ale", :lab=>"White Labs", :number=>"WLP530", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp550=>{:name=>"Belgian Ale", :lab=>"White Labs", :number=>"WLP550", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp565=>{:name=>"Belgian Saison I Ale", :lab=>"White Labs", :number=>"WLP565", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp570=>{:name=>"Belgian Golden Ale", :lab=>"White Labs", :number=>"WLP570", :type=>"Ale", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp575=>{:name=>"Belgian Style Ale Yeast Blend", :lab=>"White Labs", :number=>"WLP575", :type=>"Ale", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp715=>{:name=>"Champagne Yeast", :lab=>"White Labs", :number=>"WLP715", :type=>"Champagne", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp720=>{:name=>"Sweet Mead/Wine", :lab=>"White Labs", :number=>"WLP720", :type=>"Wine", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp727=>{:name=>"Sweet Mead/Wine", :lab=>"White Labs", :number=>"WLP727", :type=>"Wine", :form=>"Liquid", :flocculation=>"Low"},
        :white_labs_wlp775=>{:name=>"English Cider Yeast", :lab=>"White Labs", :number=>"WLP775", :type=>"Wine", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp800=>{:name=>"Pilsner Lager", :lab=>"White Labs", :number=>"WLP800", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp802=>{:name=>"Czech Budejovice Lager", :lab=>"White Labs", :number=>"WLP802", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp810=>{:name=>"San Francisco Lager", :lab=>"White Labs", :number=>"WLP810", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp820=>{:name=>"Octoberfest/Marzen Lager", :lab=>"White Labs", :number=>"WLP820", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp830=>{:name=>"German Lager", :lab=>"White Labs", :number=>"WLP830", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp833=>{:name=>"German Bock Lager", :lab=>"White Labs", :number=>"WLP833", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp838=>{:name=>"Southern German Lager", :lab=>"White Labs", :number=>"WLP838", :type=>"Lager", :form=>"Liquid", :flocculation=>"High"},
        :white_labs_wlp840=>{:name=>"American Lager", :lab=>"White Labs", :number=>"WLP840", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp862=>{:name=>"Cry Havoc", :lab=>"White Labs", :number=>"WLP862", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp885=>{:name=>"Zurich Lager", :lab=>"White Labs", :number=>"WLP885", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp920=>{:name=>"Old Bavarian Lager", :lab=>"White Labs", :number=>"WLP920", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"},
        :white_labs_wlp940=>{:name=>"Mexican Lager", :lab=>"White Labs", :number=>"WLP940", :type=>"Lager", :form=>"Liquid", :flocculation=>"Medium"}
      }
    }
  end
end
